from langchain_core.prompts import ChatPromptTemplate

from llm_config import LLMConnector
from langchain_core.tools import tool
from utils_module import log_factory

@tool
def is_related_mail(mail_text1:str, mail_text2:str):
    """validate if two emails are related mails

    :param mail_text1: the first email
    :param mail_text2: the second email
    :return: the result
    """
    logger = log_factory.get_logger()
    logger.info("start checking relationship between two email...")

    # Define a custom prompt to provide instructions and any additional context.
    # 1) You can add examples into the prompt template to improve extraction quality
    # 2) Introduce additional parameters to take context into account (e.g., include metadata
    #    about the document from which the text was extracted.)
    prompt_template = ChatPromptTemplate.from_messages(
        [
            (
                "system",
                "You are an expert email processor. "

                "Tell if mail1 and mail2 are related email "
                "If then are related email, then output 'related': true"
                "If then are related email, then output 'related': false"

                "please transform the output to json without json type tag"

                "Below is mail properties definition: "
                "1. The header field In-Reply-To contains the message ID of the email that the current message is a response to."
                "2. The header field References contains links to previous related emails by including their unique message ID numbers."
                "3. The header field Message-ID is generated by mail system to identify email"
                "4.1 A mail thread, also known as an email thread or email chain, is a series of related emails grouped together as part of the same conversation."
                "4.2 Mail thread starts with an original email and includes all subsequent replies and forwards, allowing users to follow the discussion easily."
                "4.3 Essentially, mail thread organizes the communication around a specific topic or subject line, making it easier to track responses."

                "Below is business definition, if one of the condition satisfied below, then two emails might be related emails "
                "1. If two emails are related email, then they are in same mail thread."
                "2. If two emails are related email, then their References might contain some of the same Message ID parts."
                "3. If two emails are related email, then their Subject might be the same or contains the same key information."
                "4. If two emails are related email, then their email content might be smooth as context."
                ,
            ),
            # Please see the how-to about improving performance with
            # reference examples.
            # MessagesPlaceholder('examples'),
            ("human", "{text}"),
        ]
    )

    # get llm connection
    llm = LLMConnector.get_llm()
    prompt = prompt_template.invoke({"text": "{ mail1: " + mail_text1 + ", mail2: " + mail_text2 + " }"})
    mail = llm.invoke(prompt)
    result = mail.model_dump()
    logger.info("check result: "+str(result))

    return result.get("content")